# Generated by Django 5.1.4 on 2024-12-14 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='deportes/')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='equipos/')),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ligas/')),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaapi.deporte')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcador1', models.IntegerField(default=0)),
                ('marcador2', models.IntegerField(default=0)),
                ('fecha_hora', models.DateTimeField()),
                ('duracion_minutos', models.IntegerField()),
                ('estado', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'En Juego'), (2, 'Finalizado'), (3, 'Cancelado')], default=0)),
                ('equipo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_equipo1', to='sistemaapi.equipo')),
                ('equipo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_equipo2', to='sistemaapi.equipo')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaapi.liga')),
            ],
        ),
        migrations.CreateModel(
            name='EventoPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('minuto', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaapi.equipo')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaapi.partido')),
            ],
        ),
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('tipo_apuesta', models.IntegerField(choices=[(0, 'Ganador'), (1, 'Empate')])),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Ganador'), (2, 'Perdedor'), (3, 'Cancelado')], default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaapi.equipo')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaapi.partido')),
            ],
        ),
    ]
