# Generated by Django 5.1.4 on 2024-12-14 21:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuesta',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
