# Generated by Django 5.1.4 on 2024-12-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaapi', '0002_apuesta_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuesta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
