# Generated by Django 5.1.4 on 2024-12-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaapi', '0004_alter_deporte_imagen_alter_equipo_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuesta',
            name='multiplicador',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
    ]
