# Generated by Django 5.1.4 on 2024-12-15 07:40

import sistemaapi.models.deporte
import sistemaapi.models.equipo
import sistemaapi.models.liga
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaapi', '0005_apuesta_multiplicador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deporte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=sistemaapi.models.deporte.deporte_image_upload_path),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=sistemaapi.models.equipo.equipo_image_upload_path),
        ),
        migrations.AlterField(
            model_name='liga',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=sistemaapi.models.liga.liga_image_upload_path),
        ),
    ]
